Models/Menu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class Menu
    {

        public int Id { get; set; }
        public string MealName { get; set; }
        public int MealPrice { get; set; }
        public int Quantity { get; internal set; }
    }
}

Models/MenuType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class MenuType
    {
        public string ID { get; set; }
        public string Name { get; set; }
      
    }
}

Models/MenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class MenuViewModel
    {
        internal object name;
        public List<Menus> menus { get; set; }
        public List<MenuType> menuType { get; set; }
        //public List<Slider> sliders { get; set; }
        public List<SpecialMenu> specialMenus { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Models/Menus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class Menus
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        [ForeignKey("MenuTypeID")]
        public MenuType Type { get; set; }
        public string MenuTypeID { get; set; }
        public string Image { get; set; }
        public string menuList { get; set; }
    }
}

Models/MenusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class MenusViewModel : Menus
    {
        //IEnumerable<Menus> IenumerableMenus{ get; set; }
        public List<Menus> menulistVM { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public List<MenuType> menuTypesList { get; set; }
        //public int countMenu { get; set; }
        public bool flagElement {get; set;}
    }
}

ViewModels/MenuViewModel.cs
using Hangar.Restaurant.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.ViewModels
{
    public class MenuViewModel
    {
        internal object name;
        public List<Menus> menus { get; set; }
        public List<MenuType> menuType { get; set; }
        public List<Slider> sliders { get; set; }
        public List<SpecialMenus> specialMenus { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Controllers/MenuController.cs
using Hangar.Restaurant.Contracts;
using Hangar.Restaurant.Database.Models;
using Hangar.Restaurant.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;

namespace Hangar.Restaurant.Controllers
{
    
    public class MenuController : Controller
    {
        private IRepositoryBase<MenuEntity> menuContext;
        private IRepositoryBase<MenuSectionEntity> sectionContext;
        private IRepositoryBase<MenuTypeEntity> typeContext;

        public MenuController(IRepositoryBase<MenuEntity> menuCon, IRepositoryBase<MenuSectionEntity> secCon,
            IRepositoryBase<MenuTypeEntity> typeCon)
        {
            menuContext = menuCon;
            sectionContext = secCon;
            typeContext = typeCon;
        }

        // GET: Menu
        public PartialViewResult Index()
        {
            int initTake = 3;

            MenuSectionEntity menuData = sectionContext.Collection().FirstOrDefault();
            MenuSection section = new MenuSection();

            List<MenuEntity> menus = menuContext.Collection().Include(t => t.Type).OrderBy(p => p.Price).Take(initTake).ToList();
            List<Menu> menuListModel = new List<Menu>();

            List<MenuTypeEntity> menuTypes = typeContext.Collection().ToList();
            List<MenuType> menuTypeList = new List<MenuType>();

            MenuEntity menuCheck = menuContext.Collection().Include(t => t.Type).OrderBy(p => p.Price).Skip(initTake).Take(1).FirstOrDefault();
        
            bool hasNextElemnt = false;

            if( menuCheck != null)
            {
                hasNextElemnt = true;
            }

            if (menuData != null)
            {
                section.Title = menuData.Title;
                section.Description = menuData.Description;

            }

            if(menus != null)
            {
                foreach (var item in menus)
                {

                    menuListModel.Add(new Menu()
                    {
                        Name = item.Name,
                        Description = item.Description,
                        Price = item.Price,
                        Image = item.Image,
                        Type = new MenuType() { name = item.Type.name.ToLower() }

                    }); ;
                }
            }
            
            if(menuTypes != null)
            {
                foreach (var type in menuTypes)
                {
                    //menuTypeList and menuCount must have same order
                    menuTypeList.Add(new MenuType
                    {
                        name = type.name.ToLower()
                    });
                }
            }
            

            //define model to display in view
            SectionVM model = new SectionVM()
            {
                menuList = menuListModel,
                Title = section.Title,
                Description = section.Description,
                typeList = menuTypeList,
                hasNext = hasNextElemnt
            };

            return PartialView(model);
        }

        [WebMethod]
        [HttpPost]
        [AllowAnonymous]
        public JsonResult loadMenu(int skip, string type)
        {

            List<MenuEntity> menus;
            List<Menu> menuListModel = new List<Menu>();
            MenuEntity menuCheck = new MenuEntity();
            bool hasNext = false;
            int initTake = 3;

            if (type == "all")
            {
                menus = menuContext.Collection().OrderBy(p => p.Price).Skip(skip).Take(initTake).Include(ent => ent.Type).ToList();
                menuCheck = menuContext.Collection().OrderBy(p => p.Price).Skip(skip + initTake).Take(1).FirstOrDefault();
                if ( menuCheck != null)
                {
                    hasNext = true;
                }
            }
            else
            {
                menus = menuContext.Collection()
                    .Include(ent => ent.Type)
                    .Where(m => m.Type.name == type)
                    .OrderBy(p => p.Price)
                    .Skip(skip)
                    .Take(initTake)
                    .ToList();
                menuCheck = menuContext.Collection().Where(m => m.Type.name == type).OrderBy(p => p.Price).Skip(skip + initTake).Take(1).FirstOrDefault();
                
                if (menuCheck != null)
                {
                    hasNext = true;
                }
            }
            

            if (menus != null)
            {
                foreach (var item in menus)
                {

                    menuListModel.Add(new Menu()
                    {
                        Name = item.Name,
                        Description = item.Description,
                        Price = item.Price,
                        Image = item.Image,
                        Type = new MenuType() { name = item.Type.name.ToLower() }

                    }); ;
                }
            }

            return Json(new { menuListModel, hasNext });
        }
        
        [WebMethod]
        [HttpPost]
        [AllowAnonymous]
        public JsonResult OtherTabs(string type)
        {
            int initTake = 1;
            List<MenuEntity> menuList = menuContext.Collection()
                .Include(t => t.Type)
                .OrderBy(p => p.Price)
                .Where(t => t.Type.name == type)
                .Take(initTake)
                .ToList();
            List<Menu> menuListModel = new List<Menu>();
            MenuEntity menuCheck = menuContext.Collection()
                .Include(t => t.Type)
                .Where(t => t.Type.name == type)
                .OrderBy(p => p.Price)
                .Skip(initTake)
                .Take(1)
                .FirstOrDefault();
            bool hasNext = false;

            if (menuCheck != null)
            {
                hasNext = true;
            }

            if (menuList != null)
            {
                foreach(var menu in menuList)
                {
                    menuListModel.Add(new Menu
                    {
                        Name = menu.Name,
                        Description = menu.Description,
                        Image = menu.Image,
                        Price = menu.Price,
                        Type = new MenuType { name = menu.Type.name }
                    });
                }
            }
            return Json(new {menuListModel, hasNext});
        }
    }
}

Controllers/MenusController.cs
using Hangar.Restaurant.Database;
using Hangar.Restaurant.DB.Database.Models;
using Hangar.Restaurant.DB.Repository;
using Hangar.Restaurant.Models;
using Hangar.Restaurant.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Hangar.Restaurant.Controllers
{
    public class MenusController : Controller
    {
        // GET: Menus
        private RestaurantDbContext db = new RestaurantDbContext();

        private IRepository<MenusEntity> menuContext;
        private IRepository<MenuTypeEntity> menuTypeContext;
        private IRepository<SpecialMenusEntity> specialMenuContext;

        public MenusController(IRepository<MenusEntity> mContext, IRepository<MenuTypeEntity> mtContext, IRepository<SpecialMenusEntity> smContext)
        {
            menuContext = mContext;
            menuTypeContext = mtContext;
            specialMenuContext = smContext;
        }

        // GET: Menus
        public ActionResult FetchMenu()
        {
            SpecialMenus special = new SpecialMenus();
            MenuType menuType = new MenuType();
            SpecialMenusEntity smData = specialMenuContext.Collection().FirstOrDefault();

            List<MenusEntity> menuList = menuContext.Collection().Include(ent => ent.Type).Take(9).ToList();
            //List<SpecialMenusEntity> specialList = specialMenuContext.Collection().Include(ent => ent.Id).ToList();
            List<MenuTypeEntity> menuTypeList = menuTypeContext.Collection().ToList();
            List<Menus> MenusModel = new List<Menus>();
            List<MenuType> MenuTypeModel = new List<MenuType>();
            List<SpecialMenus> smenuModel = new List<SpecialMenus>();

            if (smData != null)
            {
                special.Title = smData.Title;
                special.Description = smData.Description;
            }

            foreach (var item in menuList)
            {
                MenusModel.Add(new Menus()
                {
                    Name = item.Name,
                    Description = item.Description,
                    Price = item.Price,
                    Image = item.Image,
                    Typex = new MenuType() { Name = item.Type.Name}
                    
                });
            }
            foreach (var type in menuTypeList)
            {
                MenuTypeModel.Add(new MenuType()
                {
                    Name = type.Name
                });
            }
            MenuViewModel model = new MenuViewModel()
            {
                menus = MenusModel,
                menuType = MenuTypeModel,
                name = menuType.Name,
                Title = special.Title,
                Description = special.Description
            };
            return PartialView("~/Views/PartialView/Menus.cshtml", model);
        }
    }
}

Controllers/NavigationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Hangar.Restaurant.Controllers
{
    public class NavigationController : Controller
    {
        // GET: Nav
        public PartialViewResult Index()
        {
            //get parent controller name to display on banner
            string control = ViewBag.controller = ControllerContext.ParentActionViewContext.RouteData.Values["controller"].ToString();
            string active = "active";

            if(control == "Reservation" || control == "Stuff" || control == "Gallery")
            {
                ViewBag.dropActive = active;
            }
            else if(control == "Menu")
            {
                ViewBag.menuActive = active;
            }
            else if(control == "Home")
            {
                ViewBag.homeActive = active;
            }
            else if(control == "Dashboard")
            {
                @ViewBag.dashActive = active;
            }
            return PartialView("~/Views/Shared/Navigation.cshtml");
        }
    }
}

Views/Shared/Navigation.cshtml
<header class="top-navbar">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
            <a class="navbar-brand" href="index.html">
                <img src="~/Content/images/logo.png" alt="" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbars-rs-food" aria-controls="navbars-rs-food" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbars-rs-food">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item @ViewBag.homeActive">@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item @ViewBag.menuActive">@Html.ActionLink("Menu", "Index", "Menu", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="nav-item"><a class="nav-link" href="about.html">About</a></li>
                    <li class="nav-item dropdown @ViewBag.dropActive">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Pages</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown-a">
                            @Html.ActionLink("Reservation", "Index", "Reservation", new { area = "" }, new { @class = "dropdown-item" })
                            <a class="dropdown-item" href="stuff.html">Stuff</a>
                            <a class="dropdown-item" href="gallery.html">Gallery</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Blog</a>
                        <div class="dropdown-menu" aria-labelledby="dropdown-a">
                            <a class="dropdown-item" href="blog.html">blog</a>
                            <a class="dropdown-item" href="blog-details.html">blog Single</a>
                        </div>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
                    @if(User.Identity.Name == null|| User.Identity.Name == "")
                    {
                    <li class="nav-item @ViewBag.dashActive">@Html.ActionLink("Login", "Login", "Dashboard", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                    else
                    {
                    <li class="nav-item @ViewBag.dashActive">@Html.ActionLink("Account", "Edit", "Dashboard", new { area = "" }, new { @class = "nav-link" })</li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>

Views/Shared/_LayoutGeneral.cshtml
<!DOCTYPE html>
<html lang="en">
<!-- Basic -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Site Metas -->
    <title>Live Dinner Restaurant - Responsive HTML5 Template</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Site Icons -->
    <link rel="shortcut icon" href="Content/images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" href="Content/images/apple-touch-icon.png">

    @Styles.Render("~/Content/css")
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>


<body onload="checkLoadMore('load')">
    <!-- Start header -->
    @{ 
        Html.RenderAction("Index", "Navigation");
    }
    <!-- End header -->
    <!-- Start All Pages -->
    @{ 
        Html.RenderAction("GeneralBanner", "banner");
    }
    <!-- End All Pages -->
    <!-- Start Menu -->
    @RenderBody()
    <!-- End Menu -->
    <!-- Start Customer Reviews -->
    <div class="customer-reviews-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="heading-title text-center">
                        <h2>Customer Reviews</h2>
                        <p>Lorem Ipsum is simply dummy text of the printing and typesetting</p>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-8 mr-auto ml-auto text-center">
                    <div id="reviews" class="carousel slide" data-ride="carousel">
                        <div class="carousel-inner mt-4">
                            <div class="carousel-item text-center active">
                                <div class="img-box p-1 border rounded-circle m-auto">
                                    <img class="d-block w-100 rounded-circle" src="~/Content/images/quotations-button.png" alt="">
                                </div>
                                <h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Paul Mitchel</strong></h5>
                                <h6 class="text-dark m-0">Web Developer</h6>
                                <p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
                            </div>
                            <div class="carousel-item text-center">
                                <div class="img-box p-1 border rounded-circle m-auto">
                                    <img class="d-block w-100 rounded-circle" src="~/Content/images/quotations-button.png" alt="">
                                </div>
                                <h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Steve Fonsi</strong></h5>
                                <h6 class="text-dark m-0">Web Designer</h6>
                                <p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
                            </div>
                            <div class="carousel-item text-center">
                                <div class="img-box p-1 border rounded-circle m-auto">
                                    <img class="d-block w-100 rounded-circle" src="~/Content/images/quotations-button.png" alt="">
                                </div>
                                <h5 class="mt-4 mb-0"><strong class="text-warning text-uppercase">Daniel vebar</strong></h5>
                                <h6 class="text-dark m-0">Seo Analyst</h6>
                                <p class="m-0 pt-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam eu sem tempor, varius quam at, luctus dui. Mauris magna metus, dapibus nec turpis vel, semper malesuada ante. Idac bibendum scelerisque non non purus. Suspendisse varius nibh non aliquet.</p>
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#reviews" role="button" data-slide="prev">
                            <i class="fa fa-angle-left" aria-hidden="true"></i>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#reviews" role="button" data-slide="next">
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Customer Reviews -->
    <!-- Start Contact info -->
    <div class="contact-imfo-box">
        <div class="container">
            <div class="row">
                <div class="col-md-4 arrow-right">
                    <i class="fa fa-volume-control-phone"></i>
                    <div class="overflow-hidden">
                        <h4>Phone</h4>
                        <p class="lead">
                            +01 123-456-4590
                        </p>
                    </div>
                </div>
                <div class="col-md-4 arrow-right">
                    <i class="fa fa-envelope"></i>
                    <div class="overflow-hidden">
                        <h4>Email</h4>
                        <p class="lead">
                            yourmail@gmail.com
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <i class="fa fa-map-marker"></i>
                    <div class="overflow-hidden">
                        <h4>Location</h4>
                        <p class="lead">
                            800, Lorem Street, US
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Contact info -->
    <!-- Start Footer -->
    <footer class="footer-area bg-f">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <h3>About Us</h3>
                    <p>Integer cursus scelerisque ipsum id efficitur. Donec a dui fringilla, gravida lorem ac, semper magna. Aenean rhoncus ac lectus a interdum. Vivamus semper posuere dui.</p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h3>Subscribe</h3>
                    <div class="subscribe_form">
                        <form class="subscribe_form">
                            <input name="EMAIL" id="subs-email" class="form_input" placeholder="Email Address..." type="email">
                            <button type="submit" class="submit">SUBSCRIBE</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                    <ul class="list-inline f-social">
                        <li class="list-inline-item"><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-linkedin" aria-hidden="true"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-google-plus" aria-hidden="true"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h3>Contact information</h3>
                    <p class="lead">Ipsum Street, Lorem Tower, MO, Columbia, 508000</p>
                    <p class="lead"><a href="#">+01 2000 800 9999</a></p>
                    <p><a href="#"> info@admin.com</a></p>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h3>Opening hours</h3>
                    <p><span class="text-color">Monday: </span>Closed</p>
                    <p><span class="text-color">Tue-Wed :</span> 9:Am - 10PM</p>
                    <p><span class="text-color">Thu-Fri :</span> 9:Am - 10PM</p>
                    <p><span class="text-color">Sat-Sun :</span> 5:PM - 10PM</p>
                </div>
            </div>
        </div>

        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="company-name">
                            All Rights Reserved. &copy; 2018 <a href="#">Live Dinner Restaurant</a> Design By :
                            <a href="https://html.design/">html design</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>

    </footer>
    <!-- End Footer -->

    <a href="#" id="back-to-top" title="Back to top" style="display: none;"><i class="fa fa-paper-plane-o" aria-hidden="true"></i></a>

    <!-- ALL JS FILES -->
    @Scripts.Render("~/Content/js")
    @RenderSection("scripts", required: false)

    <!--Other scripts for menu-->

    <script>


        function ordering(type) {
            var toSortObj = document.getElementsByClassName('all');
            toSortObj = Array.prototype.slice.call(toSortObj, 0);


            if (type == "name") {
                //string sorting
                toSortObj.sort(function (a, b) {
                    var aTmp = a.getElementsByClassName(type)[0].innerHTML.toLowerCase();
                    var bTmp = b.getElementsByClassName(type)[0].innerHTML.toLowerCase();

                    console.log(aTmp, bTmp);

                    // two elements never have the same ID hence this is sufficient:
                    return (aTmp > bTmp) ? 1 : -1;
                });
            } else if (type == "price") {
                //int sorting
                toSortObj.sort(function (a, b) {
                    var aTmp = a.getElementsByClassName('price')[0].innerHTML.toLowerCase().split("$")[1];
                    var bTmp = b.getElementsByClassName('price')[0].innerHTML.toLowerCase().split("$")[1];

                    // two elements never have the same ID hence this is sufficient:
                    return (bTmp - aTmp);
                });
            } else if (type == "type") {
                //int sorting
                toSortObj.sort(function (a, b) {
                    var aTmp = a.children[0].classList[2];
                    var bTmp = b.children[0].classList[2];

                    console.log(aTmp, bTmp);

                    // two elements never have the same ID hence this is sufficient:
                    return (aTmp > bTmp) ? 1 : -1;
                });
            }




            var parent = document.getElementsByClassName('all-parent')[0];
            parent.innerHTML = "";

            for (var i = 0; i < toSortObj.length; i++) {
                parent.appendChild(toSortObj[i]);
            }
        }



    </script>
</body>
</html>