Models/Menu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class Menu
    {

        public int Id { get; set; }
        public string MealName { get; set; }
        public int MealPrice { get; set; }
        public int Quantity { get; internal set; }
    }
}

Models/MenuType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class MenuType
    {
        public string ID { get; set; }
        public string Name { get; set; }
      
    }
}

Models/MenuViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class MenuViewModel
    {
        internal object name;
        public List<Menus> menus { get; set; }
        public List<MenuType> menuType { get; set; }
        //public List<Slider> sliders { get; set; }
        public List<SpecialMenu> specialMenus { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Models/Menus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class Menus
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Description { get; set; }
        [ForeignKey("MenuTypeID")]
        public MenuType Type { get; set; }
        public string MenuTypeID { get; set; }
        public string Image { get; set; }
        public string menuList { get; set; }
    }
}

Models/MenusViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.Models
{
    public class MenusViewModel : Menus
    {
        //IEnumerable<Menus> IenumerableMenus{ get; set; }
        public List<Menus> menulistVM { get; set; }
        public string Title { get; set; }
        public string Descriptions { get; set; }
        public List<MenuType> menuTypesList { get; set; }
        //public int countMenu { get; set; }
        public bool flagElement {get; set;}
    }
}

ViewModels/MenuViewModel.cs
using Hangar.Restaurant.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Common.CommandTrees;
using System.Linq;
using System.Web;

namespace Hangar.Restaurant.ViewModels
{
    public class MenuViewModel
    {
        internal object name;
        public List<Menus> menus { get; set; }
        public List<MenuType> menuType { get; set; }
        public List<Slider> sliders { get; set; }
        public List<SpecialMenus> specialMenus { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

Controllers/AzController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Hangar.Restaurant.Controllers
{
    public class AzController : Controller
    {
        // GET: Az
        public async Task<ActionResult> Index()
        {
            var azureClient = new HttpClient();
            var result = await azureClient.GetAsync(ConfigurationManager.AppSettings["AzureFunctionURL"]);
            var content = await result.Content.ReadAsStringAsync();

            ViewBag.cont = content;

            return View();
        }
    }
}

Controllers/MenuController.cs
using Hangar.Restaurant.Contracts;
using Hangar.Restaurant.Database.Models;
using Hangar.Restaurant.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;

namespace Hangar.Restaurant.Controllers
{
    
    public class MenuController : Controller
    {
        private IRepositoryBase<MenuEntity> menuContext;
        private IRepositoryBase<MenuSectionEntity> sectionContext;
        private IRepositoryBase<MenuTypeEntity> typeContext;

        public MenuController(IRepositoryBase<MenuEntity> menuCon, IRepositoryBase<MenuSectionEntity> secCon,
            IRepositoryBase<MenuTypeEntity> typeCon)
        {
            menuContext = menuCon;
            sectionContext = secCon;
            typeContext = typeCon;
        }

        // GET: Menu
        public PartialViewResult Index()
        {
            int initTake = 3;

            MenuSectionEntity menuData = sectionContext.Collection().FirstOrDefault();
            MenuSection section = new MenuSection();

            List<MenuEntity> menus = menuContext.Collection().Include(t => t.Type).OrderBy(p => p.Price).Take(initTake).ToList();
            List<Menu> menuListModel = new List<Menu>();

            List<MenuTypeEntity> menuTypes = typeContext.Collection().ToList();
            List<MenuType> menuTypeList = new List<MenuType>();

            MenuEntity menuCheck = menuContext.Collection().Include(t => t.Type).OrderBy(p => p.Price).Skip(initTake).Take(1).FirstOrDefault();
        
            bool hasNextElemnt = false;

            if( menuCheck != null)
            {
                hasNextElemnt = true;
            }

            if (menuData != null)
            {
                section.Title = menuData.Title;
                section.Description = menuData.Description;

            }

            if(menus != null)
            {
                foreach (var item in menus)
                {

                    menuListModel.Add(new Menu()
                    {
                        Name = item.Name,
                        Description = item.Description,
                        Price = item.Price,
                        Image = item.Image,
                        Type = new MenuType() { name = item.Type.name.ToLower() }

                    }); ;
                }
            }
            
            if(menuTypes != null)
            {
                foreach (var type in menuTypes)
                {
                    //menuTypeList and menuCount must have same order
                    menuTypeList.Add(new MenuType
                    {
                        name = type.name.ToLower()
                    });
                }
            }
            

            //define model to display in view
            SectionVM model = new SectionVM()
            {
                menuList = menuListModel,
                Title = section.Title,
                Description = section.Description,
                typeList = menuTypeList,
                hasNext = hasNextElemnt
            };

            return PartialView(model);
        }

        [WebMethod]
        [HttpPost]
        [AllowAnonymous]
        public JsonResult loadMenu(int skip, string type)
        {

            List<MenuEntity> menus;
            List<Menu> menuListModel = new List<Menu>();
            MenuEntity menuCheck = new MenuEntity();
            bool hasNext = false;
            int initTake = 3;

            if (type == "all")
            {
                menus = menuContext.Collection().OrderBy(p => p.Price).Skip(skip).Take(initTake).Include(ent => ent.Type).ToList();
                menuCheck = menuContext.Collection().OrderBy(p => p.Price).Skip(skip + initTake).Take(1).FirstOrDefault();
                if ( menuCheck != null)
                {
                    hasNext = true;
                }
            }
            else
            {
                menus = menuContext.Collection()
                    .Include(ent => ent.Type)
                    .Where(m => m.Type.name == type)
                    .OrderBy(p => p.Price)
                    .Skip(skip)
                    .Take(initTake)
                    .ToList();
                menuCheck = menuContext.Collection().Where(m => m.Type.name == type).OrderBy(p => p.Price).Skip(skip + initTake).Take(1).FirstOrDefault();
                
                if (menuCheck != null)
                {
                    hasNext = true;
                }
            }
            

            if (menus != null)
            {
                foreach (var item in menus)
                {

                    menuListModel.Add(new Menu()
                    {
                        Name = item.Name,
                        Description = item.Description,
                        Price = item.Price,
                        Image = item.Image,
                        Type = new MenuType() { name = item.Type.name.ToLower() }

                    }); ;
                }
            }

            return Json(new { menuListModel, hasNext });
        }
        
        [WebMethod]
        [HttpPost]
        [AllowAnonymous]
        public JsonResult OtherTabs(string type)
        {
            int initTake = 1;
            List<MenuEntity> menuList = menuContext.Collection()
                .Include(t => t.Type)
                .OrderBy(p => p.Price)
                .Where(t => t.Type.name == type)
                .Take(initTake)
                .ToList();
            List<Menu> menuListModel = new List<Menu>();
            MenuEntity menuCheck = menuContext.Collection()
                .Include(t => t.Type)
                .Where(t => t.Type.name == type)
                .OrderBy(p => p.Price)
                .Skip(initTake)
                .Take(1)
                .FirstOrDefault();
            bool hasNext = false;

            if (menuCheck != null)
            {
                hasNext = true;
            }

            if (menuList != null)
            {
                foreach(var menu in menuList)
                {
                    menuListModel.Add(new Menu
                    {
                        Name = menu.Name,
                        Description = menu.Description,
                        Image = menu.Image,
                        Price = menu.Price,
                        Type = new MenuType { name = menu.Type.name }
                    });
                }
            }
            return Json(new {menuListModel, hasNext});
        }
    }
}

Controllers/MenuPageController.cs
using Hangar.Restaurant.Database;
using Hangar.Restaurant.DB.Database.Models;
using Hangar.Restaurant.DB.Repository;
using Hangar.Restaurant.Models;
using Hangar.Restaurant.ViewModels;
using Microsoft.Ajax.Utilities;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Hangar.Restaurant.Controllers
{
    public class MenuPageController : Controller
    {
        private RestaurantDbContext db = new RestaurantDbContext();

        private IRepository<MenusEntity> menuContext;
        private IRepository<MenuTypeEntity> menuTypeContext;
        private IRepository<SpecialMenusEntity> specialMenuContext;

        public MenuPageController(IRepository<MenusEntity> mContext, IRepository<MenuTypeEntity> mtContext, IRepository<SpecialMenusEntity> smContext)
        {
            menuContext = mContext;
            menuTypeContext = mtContext;
            specialMenuContext = smContext;
        }
        // GET: MenuPage
        public ActionResult MenuLayout()
        {
            SpecialMenus special = new SpecialMenus();
            MenuType menuType = new MenuType();
            SpecialMenusEntity smData = specialMenuContext.Collection().FirstOrDefault();

            //List<MenusEntity> menuList = menuContext.Collection().Include(ent => ent.Type).OrderBy(p => p.Id).Take(9).ToList();
            List<MenusEntity> menuList = menuContext.Collection().Include(t => t.Type).OrderBy(p => p.Id).Take(9).ToList();

            //List<SpecialMenusEntity> specialList = specialMenuContext.Collection().Include(ent => ent.Id).ToList();
            List<MenuTypeEntity> menuTypeList = menuTypeContext.Collection().ToList();
            List<Menus> MenusModel = new List<Menus>();
            List<MenuType> MenuTypeModel = new List<MenuType>();
            List<SpecialMenus> smenuModel = new List<SpecialMenus>();

            int menuCount = menuContext.Collection().Count();

            if (smData != null)
            {
                special.Title = smData.Title;
                special.Description = smData.Description;
            }

            foreach (var item in menuList)
            {
                MenusModel.Add(new Menus()
                {
                    Name = item.Name,
                    Description = item.Description,
                    Price = item.Price,
                    Image = item.Image,
                    Typex = new MenuType() { Name = item.Type.Name }

                });
            }
            foreach (var type in menuTypeList)
            {
                MenuTypeModel.Add(new MenuType()
                {
                    Name = type.Name
                });
            }
            MenuViewModel model = new MenuViewModel()
            {
                menus = MenusModel,
                menuType = MenuTypeModel,
                name = menuType.Name,
                Title = special.Title,
                Description = special.Description
            };
            return PartialView("~/Views/PartialView/MenuPage.cshtml", model);
        }
        public string LoadMore(int count)
        {
            var menuFetch = fetchMenu(count, 9);
            string output = JsonConvert.SerializeObject(menuFetch);
            return output;

        }
        public LoadMore fetchMenu(int skipCount, int takeCount)
        {
            LoadMore lm = new LoadMore();
            lm.ShowLoadMore = true;
            List<MenusEntity> menuList = menuContext.Collection().Include(t => t.Type).OrderBy(p => p.Id).Skip(skipCount).Take(takeCount).ToList();
            List<MenuTypeEntity> menuTypeList = menuTypeContext.Collection().ToList();
            List<Menus> MenusModel = new List<Menus>();

            foreach (var item in menuList)
            {
                MenusModel.Add(new Menus()
                {
                    Name = item.Name,
                    Description = item.Description,
                    Price = item.Price,
                    Image = item.Image,
                    Typex = new MenuType() { Name = item.Type.Name }

                });
            }
            lm.Menus = MenusModel;
            var LoadMoreFlag = menuContext.Collection().Include(t => t.Type).OrderBy(p => p.Id).Skip(skipCount + takeCount).Take(1).ToList();
            if (!LoadMoreFlag.Any())
            {
                lm.ShowLoadMore = false;
            }
            return lm;
        }
    }
}

Controllers/MenusController.cs
using Hangar.Restaurant.Database;
using Hangar.Restaurant.DB.Database.Models;
using Hangar.Restaurant.DB.Repository;
using Hangar.Restaurant.Models;
using Hangar.Restaurant.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Hangar.Restaurant.Controllers
{
    public class MenusController : Controller
    {
        // GET: Menus
        private RestaurantDbContext db = new RestaurantDbContext();

        private IRepository<MenusEntity> menuContext;
        private IRepository<MenuTypeEntity> menuTypeContext;
        private IRepository<SpecialMenusEntity> specialMenuContext;

        public MenusController(IRepository<MenusEntity> mContext, IRepository<MenuTypeEntity> mtContext, IRepository<SpecialMenusEntity> smContext)
        {
            menuContext = mContext;
            menuTypeContext = mtContext;
            specialMenuContext = smContext;
        }

        // GET: Menus
        public ActionResult FetchMenu()
        {
            SpecialMenus special = new SpecialMenus();
            MenuType menuType = new MenuType();
            SpecialMenusEntity smData = specialMenuContext.Collection().FirstOrDefault();

            List<MenusEntity> menuList = menuContext.Collection().Include(ent => ent.Type).Take(9).ToList();
            //List<SpecialMenusEntity> specialList = specialMenuContext.Collection().Include(ent => ent.Id).ToList();
            List<MenuTypeEntity> menuTypeList = menuTypeContext.Collection().ToList();
            List<Menus> MenusModel = new List<Menus>();
            List<MenuType> MenuTypeModel = new List<MenuType>();
            List<SpecialMenus> smenuModel = new List<SpecialMenus>();

            if (smData != null)
            {
                special.Title = smData.Title;
                special.Description = smData.Description;
            }

            foreach (var item in menuList)
            {
                MenusModel.Add(new Menus()
                {
                    Name = item.Name,
                    Description = item.Description,
                    Price = item.Price,
                    Image = item.Image,
                    Typex = new MenuType() { Name = item.Type.Name}
                    
                });
            }
            foreach (var type in menuTypeList)
            {
                MenuTypeModel.Add(new MenuType()
                {
                    Name = type.Name
                });
            }
            MenuViewModel model = new MenuViewModel()
            {
                menus = MenusModel,
                menuType = MenuTypeModel,
                name = menuType.Name,
                Title = special.Title,
                Description = special.Description
            };
            return PartialView("~/Views/PartialView/Menus.cshtml", model);
        }
    }
}

Views/PartialView/MenuLayout.cshtml
@*@model Hangar.Restaurant.Models.MenuSection*@
@*@model IEnumerable<Hangar.Restaurant.DB.Database.Models.MenusEntity>*@
@*@model IEnumerable<Hangar.Restaurant.DB.Database.Models.MenuTypeEntity>*@
@model Hangar.Restaurant.Models.MenuViewModel
@{Layout = "~/Views/Shared/Menu.cshtml";}

<div class="menu-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">

                    <h2>@Model.Title</h2>
                    <p>@Model.Description</p>

                </div>
            </div>
        </div>

        <div class="row inner-menu-box">
            <div class="col-3">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">All</a>
                    @foreach (var item in Model.menuType)
                    {
                        <a class="nav-link" id="@item.Name-tab" data-toggle="pill" href="#@item.Name" role="tab" aria-controls="@item.Name" aria-selected="false">@item.Name</a>

                    }
                    @*<a class="nav-link" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-profile" aria-selected="false">Drinks</a>
                        <a class="nav-link" id="v-pills-messages-tab" data-toggle="pill" href="#v-pills-messages" role="tab" aria-controls="v-pills-messages" aria-selected="false">Lunch</</a>
                        <a class="nav-link" id="v-pills-settings-tab" data-toggle="pill" href="#v-pills-settings" role="tab" aria-controls="v-pills-settings" aria-selected="false">Dinner</a>*@
                </div>
            </div>
            <div class="col-9">
                <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                        <div class="row">
                            @foreach (var item in Model.menus)
                            {
                                <div class="col-lg-4 col-md-6 special-grid">
                                    <div class="gallery-single fix">
                                        <img src="../@Html.DisplayFor(modelItem => item.Image)" class="img-fluid" alt="Image">
                                        <div class="why-text">
                                            <h4>@Html.DisplayFor(modelItem => item.Name)</h4>
                                            <p>@Html.DisplayFor(modelItem => item.Description)</p>
                                            <h5>$@Html.DisplayFor(modelItem => item.Price)</h5>
                                        </div>
                                    </div>
                                </div>
                            }

                        </div>

                    </div>
                    @foreach (var types in Model.menuType)
                    {
                        <div class="tab-pane fade" id="@types.Name" role="tabpanel" aria-labelledby="@types.Name-tab">
                            <div class="row">
                                @foreach (var item in Model.menus)
                                {
                                    if (item.Type.Name == types.Name)
                                    {
                                        <div class="col-lg-4 col-md-6 special-grid @types.Name">
                                            <div class="gallery-single fix">
                                                <img src="../@Html.DisplayFor(modelItem => item.Image)" class="img-fluid" alt="Image">
                                                <div class="why-text">
                                                    <h4>@Html.DisplayFor(modelItem => item.Name)</h4>
                                                    <p>@Html.DisplayFor(modelItem => item.Description)</p>
                                                    <h5>$@Html.DisplayFor(modelItem => item.Price)</h5>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                }

                            </div>
                        </div>
                    }
                </div>

            </div>
        </div>

    </div>
</div>

Views/PartialView/MenuPage.cshtml
@model Hangar.Restaurant.ViewModels.MenuViewModel
@{ Layout = "~/Views/Shared/LayoutMenu.cshtml";}
    
<div class="menu-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">

                    <h2>@Model.Title</h2>
                    <p>@Model.Description</p>

                </div>
            </div>
        </div>

        
        
        <div class="row inner-menu-box">
            <div class="col-3">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <div>
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="dropdown-a" data-toggle="dropdown">Sort by</a>
                                <div class="dropdown-menu" aria-labelledby="dropdown-a">
                                    <a class="dropdown-item" href="">Price</a>
                                    <a class="dropdown-item" href="">Name</a>
                                    <a class="dropdown-item" href="">Type</a>
                                </div>
                            </li>
                        </ul>
                    </div>

                    <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">All</a>
                    @foreach (var item in Model.menuType)
                    {
                        <a class="nav-link" id="@item.Name-tab" data-toggle="pill" href="#@item.Name" role="tab" aria-controls="@item.Name" aria-selected="false">@item.Name</a>

                    }

                </div>
            </div>
            
                <div class="col-9">
                    <div class="tab-content" id="v-pills-tabContent">
                        <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                            <div class="row">
                                @foreach (var item in Model.menus)
                                {
                                    <div class="col-lg-4 col-md-6 special-grid @item.Typex">
                                        <div class="gallery-single fix">
                                            <img src="../@Html.DisplayFor(modelItem => item.Image)" class="img-fluid" alt="Image">
                                            <div class="why-text">
                                                <h4>@Html.DisplayFor(modelItem => item.Name)</h4>
                                                <p>@Html.DisplayFor(modelItem => item.Description)</p>
                                                <h5>$@Html.DisplayFor(modelItem => item.Price)</h5>
                                            </div>
                                        </div>
                                    </div>
                                }

                            </div>

                        </div>

                        @foreach (var types in Model.menuType)
                        {
                            <div class="tab-pane fade" id="@types.Name" role="tabpanel" aria-labelledby="@types.Name-tab">
                                <div class="row" id="loadMenu">
                                    @foreach (var item in Model.menus)
                                    {
                                        if (item.Typex.Name == types.Name)
                                        {
                                            <div class="col-lg-4 col-md-6 special-grid @types.Name">
                                                <div class="gallery-single fix">
                                                    <img src="../@Html.DisplayFor(modelItem => item.Image)" class="img-fluid" alt="Image">
                                                    <div class="why-text">
                                                        <h4>@Html.DisplayFor(modelItem => item.Name)</h4>
                                                        <p>@Html.DisplayFor(modelItem => item.Description)</p>
                                                        <h5>$@Html.DisplayFor(modelItem => item.Price)</h5>
                                                    </div>
                                                </div>
                                            </div>
                                        }
                                    }

                                </div>
                             </div>

                        }
                        <div id="loadmenu"></div>
                        <a class="btn btn-info js_LoadMore" href="">Load More</a>

                        @*@Ajax.ActionLink("Load More", "", "", new AjaxOptions()
        {
            HttpMethod = "POST",
            InsertionMode = InsertionMode.Replace,
            UpdateTargetId = ""
        },
        new { @class = "btn btn-info" }
        )*@
                    </div>
                    </div>
        </div>
    </div>
</div>
<script src="~/Content/js/jquery-3.2.1.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

Views/PartialView/Menus.cshtml
@model Hangar.Restaurant.Models.SectionVM
<div class="menu-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="heading-title text-center">
                    <h2>@Model.Title</h2>
                    <p>@Model.Description</p>
                </div>
            </div>
        </div>

        <div class="row inner-menu-box">
            <div class="col-3">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                    <a class="nav-link active" id="v-pills-home-tab" data-toggle="pill" href="#v-pills-home" role="tab" aria-controls="v-pills-home" aria-selected="true">All</a>
                    @foreach (var type in Model.typeList)
                    {
                    <a class="nav-link" id="@type.name-tab" data-toggle="pill" href="#@type.name" role="tab" aria-controls="@type.name" aria-selected="false">
                        <!-- Display first char Uppercase and remaining in lowercase -->
                        @type.name.Substring(0,1).ToUpper()@type.name.Substring(1)
                    </a>
                    }
                </div>
            </div>

            <div class="col-9">
                <div class="tab-content" id="v-pills-tabContent">
                    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
                        <div class="row">
                            @foreach (var item in Model.menuList) {
                            <div class="col-lg-4 col-md-6 special-grid @item.Type.name">
                                <div class="gallery-single fix">
                                    <img src=@item.Image class="img-fluid" alt="Image">
                                    <div class="why-text">
                                        <h4>@item.Name</h4>
                                        <p>@item.Description</p>
                                        <h5> $ @item.Price </h5>
                                    </div>
                                </div>
                            </div>
                            }
                        </div>
                    </div>
                    @foreach (var type in Model.typeList)
                    {
                    <div class="tab-pane fade" id="@type.name" role="tabpanel" aria-labelledby="@type.name-tab">
                        <div class="row">
                            @foreach (var item in Model.menuList)
                            {
                                if (item.Type.name == type.name)
                                {
                                    <div class="col-lg-4 col-md-6 special-grid @item.Type.name">
                                        <div class="gallery-single fix">
                                            <img src=@item.Image class="img-fluid" alt="Image">
                                            <div class="why-text">
                                                <h4>@item.Name</h4>
                                                <p>@item.Description</p>
                                                <h5> $ @item.Price </h5>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                    }
                    @Html.ActionLink("azure","Index","Az")
                </div>
            </div>
        </div>
    </div>
</div>